import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` font-poppins antialiased`}
      >
        <main className="flex flex-col h-full justify-between">
          {children}
        </main>
      </body>
    </html>
  );
}
