import type { Metadata } from "next";
import "./globals.css";
import Header from "./header/page";
import Footer from "@/components/footer/page";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` font-poppins antialiased`}
      >
        <main className="flex flex-col justify-between">
          <Header/>
          {children}
          <Footer/>
        </main>
      </body>
    </html>
  );
}
